// ── Public appearances — talks, judging, mentoring ─────────────────────────
//
// Feeds the homepage "What's next" section (#appearances) and the site-wide
// announcement banner (lib/announcements.ts links here). Keep entries even
// after they pass — they become the historical "featured in" record. Order:
// soonest-first; the homepage section doesn't re-sort.
//
// `endsISO` is what keeps the section honest: once it passes, the entry moves
// itself out of "what's next" and into the "recently" row below — no manual
// edit needed on the day an event ends.

import type { CardCategory } from "@/lib/categories";

export type Appearance = {
  slug: string;
  role: string; // "Speaker", "Judge + Mentor", "Panelist"...
  title: string;
  org: string;
  date: string; // human-readable range, e.g. "Jul 18–19, 2026"
  endsISO: string; // instant the appearance is over; past this it reads as history
  location: string;
  // Link hierarchy, in order of preference: 1) video of the talk, 2) deck,
  // 3) conference listing for his specific session, 4) anything naming him
  // or Agile Lens by name. A generic org homepage that doesn't show what
  // role he played is worse than no link — omit `url` rather than pad it
  // with one.
  url?: string;
  image?: string; // path under /public
};

// "Official Selection" entries are work that got selected/screened, not a
// talk he personally gave — that's "Work Featured", not an attendance mode.
// Everything else splits on whether `location` says it was virtual.
export function categoryForAppearance(a: Appearance): CardCategory {
  if (a.role === "Official Selection") return "Work Featured";
  return a.location.toLowerCase().includes("virtual") ? "Virtual" : "In Person";
}

// ── Historical record (2014–2026) ───────────────────────────────────────
//
// Sourced from AgileLens's YouTube-transcript archive, the agilelens.com/media
// Wayback Machine snapshot, and confirmed event emails — see the KB at
// ~/knowledge/media/youtube/{speaking-engagements,past-talks-archive}.md and
// ~/knowledge/context/team/team-alex-full-bio.md. Kept in ascending
// chronological order so AppearancesSection's `.slice(-4).reverse()` "recently"
// picker keeps working — new past entries belong just above this comment
// block ends (i.e. right before the first upcoming/near-term entry below).
export const appearances: Appearance[] = [
  {
    slug: "nyit-intersections-2014",
    role: "Speaker",
    title: "Oculus Rift for 3D Modeling",
    org: "NYIT Intersections Symposium",
    date: "2014",
    endsISO: "2014-06-30T00:00:00Z",
    location: "New York, NY",
    url: "https://openlab.citytech.cuny.edu/fuselab/event/intersections-2014/intersections-2014-speaker-profiles/",
  },
  {
    slug: "opera-america-2014",
    role: "Speaker",
    title: "Oculus Rift Workflow Demonstration",
    org: "OPERA America National Conference",
    date: "Jun 2014",
    endsISO: "2014-06-30T00:00:00Z",
    location: "San Francisco, CA",
  },
  {
    slug: "nyvr-designing-theaters-2015",
    role: "Speaker",
    title: "Designing Theaters with VR",
    org: "NYVR Meetup",
    date: "2015",
    endsISO: "2015-06-30T00:00:00Z",
    location: "New York, NY",
    url: "https://www.youtube.com/watch?v=GhaCYfanRB4",
  },
  {
    slug: "big-picture-talk-2015",
    role: "Speaker",
    title: "BIG Picture Talk: VR + Architecture + Theaters",
    org: "Bjarke Ingels Group",
    date: "2015",
    endsISO: "2015-09-30T00:00:00Z",
    location: "New York, NY",
    url: "https://www.youtube.com/watch?v=2A1_0GKJypA",
  },
  {
    slug: "venueconnect-2016",
    role: "Panelist",
    title: "VR for Architecture, Fans, & Training",
    org: "VenueConnect",
    date: "2016",
    endsISO: "2016-08-15T00:00:00Z",
    location: "Minneapolis, MN",
    url: "https://www.youtube.com/watch?v=96CMiNrmz1E",
  },
  {
    slug: "autodesk-university-2017-first-line",
    role: "Speaker",
    title: "From First Line to Final Design: VR as the Ultimate Creative Medium",
    org: "Autodesk University",
    date: "2017",
    endsISO: "2017-11-30T00:00:00Z",
    location: "Las Vegas, NV",
    url: "https://www.autodesk.com/autodesk-university/class/First-Line-Final-Design-VR-Ultimate-Creative-Medium-2017",
  },
  {
    slug: "autodesk-university-2017-panel",
    role: "Panelist",
    title: "A Vision for the Future of Virtual Reality in Design Viz: Advice from the Experts",
    org: "Autodesk University",
    date: "2017",
    endsISO: "2017-11-30T00:00:00Z",
    location: "Las Vegas, NV",
    url: "https://www.autodesk.com/autodesk-university/class/vision-future-Virtual-Reality-Design-Viz-Advice-Experts-2017",
  },
  {
    slug: "vr2020-summit-2017",
    role: "Panel Moderator",
    title: "Virtual Reality Moves into Real Estate",
    org: "VR 20/20 Summit",
    date: "2017",
    endsISO: "2017-05-30T00:00:00Z",
    location: "New York, NY",
    url: "https://twitter.com/DipakPatel/status/919994810173394944",
  },
  {
    slug: "jump-into-vr-fest-2017",
    role: "Speaker",
    title: "Using VR Art Tools to Design Space",
    org: "Jump into VR Fest",
    date: "2017",
    endsISO: "2017-06-30T00:00:00Z",
    location: "New York, NY",
    url: "https://www.facebook.com/jumpintovrfest/videos/alex-coulombe-of-agile-lens/1752864321672970/",
  },
  {
    slug: "tcg-petting-zoo-2017",
    role: "Workshop",
    title: "Virtual Reality Petting Zoo",
    org: "Theatre Communications Group Conference",
    date: "Jun 2017",
    endsISO: "2017-06-30T00:00:00Z",
    location: "Portland, OR",
    url: "http://web.archive.org/web/20230126222427/https://www.tcg.org/Events/NationalConference/PastConferenceArchives/2017/TCGinPDX.aspx",
  },
  {
    slug: "nyvr-expo-2018",
    role: "Speaker",
    title: "NYVR Expo",
    org: "NYVR",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "vr-strategy-conference-2018",
    role: "Speaker",
    title: "Virtual Reality Strategy Conference",
    org: "VRS Conference",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "San Francisco, CA",
  },
  {
    slug: "smithsonian-vr-2018",
    role: "Speaker",
    title: "VR for Design",
    org: "The Smithsonian",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "Washington, DC",
  },
  {
    slug: "unreal-engine-london-2018",
    role: "Speaker",
    title: "UE4 for Enterprise Solutions",
    org: "Unreal Engine London",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "London, UK",
    url: "https://web.archive.org/web/20190401185507/https://skillsmatter.com/skillscasts/12229-agile-lens-immersive-design",
  },
  {
    slug: "autodesk-university-london-2018",
    role: "Speaker",
    title: "Beyond Presentations: Designing Naturally in VR",
    org: "Autodesk University London",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "London, UK",
    url: "https://www.autodesk.com/autodesk-university/class/Beyond-Presentations-Designing-Naturally-VR-2018",
  },
  {
    slug: "iteac-2018",
    role: "Speaker",
    title: "VR in Theater Design",
    org: "ITEAC",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "London, UK",
  },
  {
    slug: "im-arch-venice-2018",
    role: "Speaker",
    title: "Beyond Representation: Active Design Inside VR",
    org: "Im-Arch Venice",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "Venice, Italy",
    url: "https://youtu.be/XdUOaEQakE8",
  },
  {
    slug: "propelify-2018",
    role: "Speaker",
    title: "VR in Architecture From Conception To Completion",
    org: "Propelify Innovation Festival",
    date: "2018",
    endsISO: "2018-09-30T00:00:00Z",
    location: "Hoboken, NJ",
    url: "https://web.archive.org/web/20210806033627/https://propelify.com/festival18/",
  },
  {
    slug: "vrara-webinar-2018",
    role: "Speaker",
    title: "How to Add VR Sketching to Your Design Workflow",
    org: "VRARA — VR & AR in Architecture Engineering Construction",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "Virtual",
  },
  {
    slug: "smps-northeast-2018",
    role: "Speaker",
    title: "Virtual Reality: The Best Marketing Tool You're Not Using Yet",
    org: "SMPS Northeast Regional Conference (#MERGE)",
    date: "2018",
    endsISO: "2018-06-30T00:00:00Z",
    location: "Baltimore, MD",
    url: "https://www.youtube.com/watch?v=NI76VX3zln8",
  },
  {
    slug: "national-alliance-musical-theatre-2019",
    role: "Featured Panelist",
    title: "New Works & New Technology",
    org: "National Alliance for Musical Theatre Conference",
    date: "2019",
    endsISO: "2019-11-30T00:00:00Z",
    location: "New York, NY",
    url: "https://namt.org/events/fall-conference-2019/#agenda",
  },
  {
    slug: "state-of-art-adx-2019",
    role: "Epic Games Featured Speaker",
    title: "Virtual and Augmented Reality for Real-time Design Exploration",
    org: "State of Art ADX",
    date: "2019",
    endsISO: "2019-06-30T00:00:00Z",
    location: "Mogliano Veneto, Italy",
    url: "http://web.archive.org/web/20190918225620/https://www.stateofartacademy.com/academy-days-x/",
  },
  {
    slug: "nyc-media-lab-summit-2019",
    role: "Exhibitor",
    title: "Ghosted AR — Winner, Audience Choice",
    org: "NYC Media Lab Summit",
    date: "2019",
    endsISO: "2019-11-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "venice-film-festival-2019",
    role: "Official Selection",
    title: "Loveseat",
    org: "Venice International Film Festival",
    date: "2019",
    endsISO: "2019-09-15T00:00:00Z",
    location: "Venice, Italy",
    url: "https://realtimeconference.com/june-2020-immersive-storytelling-panel-discussion/",
  },
  {
    slug: "3ds-new-york-2019",
    role: "Speaker",
    title: "Crafting Meaningful Immersive Environments",
    org: "3ds New York",
    date: "Jul 10, 2019",
    endsISO: "2019-07-10T23:00:00Z",
    location: "New York, NY",
    url: "https://youtu.be/0khsRW5B3qQ",
  },
  {
    slug: "north-bend-film-festival-2019",
    role: "Official Selection",
    title: "Ghosted AR — Winner, Most Innovative Immersive Experience",
    org: "North Bend Film Festival",
    date: "2019",
    endsISO: "2019-09-30T00:00:00Z",
    location: "Bellingham, WA",
  },
  {
    slug: "ieee-gem-2019",
    role: "Speaker",
    title: "Making of That Kind of Guy, Alive in Plasticland",
    org: "IEEE GEM",
    date: "2019",
    endsISO: "2019-06-30T00:00:00Z",
    location: "New Haven, CT (Yale)",
  },
  {
    slug: "tcg-national-2019",
    role: "XR Curator + Speaker",
    title: "XR Curator, Speaker, Workshop, Demos",
    org: "TCG National Theatre Conference",
    date: "2019",
    endsISO: "2019-06-30T00:00:00Z",
    location: "Miami, FL",
    url: "https://circle.tcg.org/tcg19/home?ssopc=1",
  },
  {
    slug: "total-chaos-2019",
    role: "Speaker",
    title: "A Strange Symbiosis: Interactions between Architecture and VR",
    org: "Total Chaos",
    date: "2019",
    endsISO: "2019-06-30T00:00:00Z",
    location: "Sofia, Bulgaria",
    url: "https://www.youtube.com/watch?v=gWlV4NgVWjo",
  },
  {
    slug: "st-johnsbury-academy-2019",
    role: "Speaker + Workshop",
    title: "XR: Creating the Future",
    org: "St. Johnsbury Academy",
    date: "2019",
    endsISO: "2019-06-30T00:00:00Z",
    location: "St. Johnsbury, VT",
  },
  {
    slug: "sxsw-2019",
    role: "Workshop",
    title: "Producing Live Performance in VR",
    org: "SXSW",
    date: "2019",
    endsISO: "2019-03-15T00:00:00Z",
    location: "Austin, TX",
    url: "https://schedule.sxsw.com/2019/events/PP93017",
  },
  {
    slug: "immersive-architecture-asia-2019",
    role: "Speaker",
    title: "More than a View: Designing from the Inside-Out",
    org: "Im-Arch Asia",
    date: "Jan 2019",
    endsISO: "2019-01-19T00:00:00Z",
    location: "Singapore",
    url: "http://web.archive.org/web/20190823105738/https://www.im-arch.asia/schedule/",
  },
  {
    slug: "computational-aec-melbourne-2020",
    role: "Speaker",
    title: "5 Ways XR Makes You a Better Architect",
    org: "Computational AEC Melbourne",
    date: "Jun 25, 2020",
    endsISO: "2020-06-25T23:00:00Z",
    location: "Virtual (Melbourne)",
    url: "https://www.youtube.com/watch?v=es9CSYYwoTI",
  },
  {
    slug: "tcg-national-conference-2020",
    role: "XR Curator",
    title: "TCG National Conference",
    org: "Theatre Communications Group",
    date: "Jun 5, 2020",
    endsISO: "2020-06-05T23:00:00Z",
    location: "Virtual",
    url: "https://youtu.be/JT0JwnLYfmY",
  },
  {
    slug: "realtime-conference-2020-multiuser",
    role: "Presenter",
    title: "Multi-user Collaboration and VR (with Andreea Ion Cojocaru)",
    org: "RealTime Conference",
    date: "2020",
    endsISO: "2020-04-26T00:00:00Z",
    location: "Virtual",
    url: "https://youtu.be/zcrLQT9KBBU",
  },
  {
    slug: "5th-wall-forum-2020",
    role: "Co-Founder + Host",
    title: "Connector Track",
    org: "5th Wall Forum",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual",
    url: "https://www.brendanabradley.com/futurestages/2020/12/1/5th-wall-forum-reveal-virtual-conference",
  },
  {
    slug: "nxtbld-inside-out-2020",
    role: "Speaker",
    title: "How VR Helped Us Design a Theater from the Inside-Out",
    org: "NxtBld",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual",
    url: "https://youtu.be/13y52rZw9ns",
  },
  {
    slug: "here-fest-2020",
    role: "Speaker",
    title: "Here Fest",
    org: "Here Fest",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual",
  },
  {
    slug: "nyu-tisch-brendan-bradley-2020",
    role: "Instructor",
    title: "VR Live Performance",
    org: "NYU Tisch — Brendan Bradley Integrative Technology Lab",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "currents-new-media-2020",
    role: "Speaker",
    title: "XR. Theatre. Architecture.",
    org: "CURRENTS New Media Festival",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Santa Fe, NM",
  },
  {
    slug: "realtime-conference-2020-storytelling",
    role: "Track Curator + Host",
    title: "Storytelling Track",
    org: "RealTime Conference",
    date: "2020",
    endsISO: "2020-04-27T00:00:00Z",
    location: "Virtual",
    url: "https://realtime.community/june-2020-immersive-storytelling-panel-discussion/",
  },
  {
    slug: "tcg-phoenix-2020",
    role: "XR Curator",
    title: "XR Curator, Speaker, Workshop, Demos",
    org: "TCG Phoenix",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Phoenix, AZ",
  },
  {
    slug: "theatre-young-audiences-2020",
    role: "Keynote Speaker",
    title: "Theatre for a Young Audience",
    org: "TYA/USA",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual",
    url: "https://www.tyausa.org/wp-content/uploads/2020/04/Virtual-Conference-Press-Release-FINAL-2.pdf",
  },
  {
    slug: "cpd-vr-dubai-2020",
    role: "Panelist",
    title: "Continuing Professional Development in VR",
    org: "Live from Dubai",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual (Dubai)",
  },
  {
    slug: "realtime-conference-2020-architecture",
    role: "Track Curator + Host",
    title: "Architecture Track",
    org: "RealTime Conference",
    date: "2020",
    endsISO: "2020-04-28T00:00:00Z",
    location: "Virtual",
    url: "https://realtime.community/architecture-crafting-real-and-virtual-architecture-in-real-time-part-2/",
  },
  {
    slug: "arkit-meetup-mit-reality-hack-2020",
    role: "Speaker",
    title: "When I Was Little...",
    org: "ARKit Meetup / MIT Reality Hack",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Cambridge, MA",
    url: "https://devpost.com/software/the-fourth-illusion",
  },
  {
    slug: "arts-council-korea-2020",
    role: "Speaker",
    title: "Theatre and XR using Spatial — NYC to Seoul",
    org: "Arts Council Korea (ARKO)",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual (Seoul)",
    url: "https://www.youtube.com/watch?v=TXr64A6644I",
  },
  {
    slug: "head-stretcher-society-2020",
    role: "Inaugural Speaker",
    title: "It's Like You're There: Virtual and Augmented Realities in Architecture, Theatre, and Everything In Between",
    org: "Head Stretcher Society",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Virtual",
    url: "http://web.archive.org/web/20240716065319/https://thekarmabirdhouse.com/happening/alex-coulombe-its-like-youre-there/",
  },
  {
    slug: "syracuse-arc682-2020",
    role: "Instructor",
    title: "ARC 682: Media",
    org: "Syracuse University School of Architecture",
    date: "2020",
    endsISO: "2020-06-30T00:00:00Z",
    location: "Syracuse, NY",
  },
  {
    slug: "nvidia-gtc-heavenue-2021",
    role: "Speaker",
    title: "Heavenue",
    org: "NVIDIA GTC",
    date: "2021",
    endsISO: "2021-04-30T00:00:00Z",
    location: "Virtual",
    url: "https://vimeo.com/641004744/60806b3a28",
  },
  {
    slug: "nxtbld-2021-architect-metaverse",
    role: "Speaker",
    title: "An Architect in the Metaverse: Social VR, NFTs, and New Opportunities",
    org: "NxtBld 2021",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "London, UK",
    url: "https://www.youtube.com/watch?v=ulJaAzDqn9w",
  },
  {
    slug: "power-up-dance-ireland-2021",
    role: "Speaker + Panelist",
    title: "Up Close & Virtual",
    org: "POWER UP: Exploring the Intersection of Art & Technology — Dance Ireland",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Virtual (Dublin)",
    url: "https://youtu.be/X6MWshB0JL8",
  },
  {
    slug: "siggraph-2021-vr-theatre-no-budget",
    role: "Co-Presenter + Co-Author",
    title: "VR Theatre on No Budget",
    org: "SIGGRAPH",
    date: "2021",
    endsISO: "2021-08-15T00:00:00Z",
    location: "Virtual",
    url: "https://drive.google.com/file/d/1UT3y3EM-RJC5CVMi5td0l9_rufSRIEdC/view",
  },
  {
    slug: "siggraph-2021-realtime-architecture",
    role: "Speaker",
    title: "RealTime Architecture Perspectives",
    org: "SIGGRAPH",
    date: "2021",
    endsISO: "2021-08-15T00:00:00Z",
    location: "Virtual",
    url: "https://youtu.be/PhJ_5CdKWkU",
  },
  {
    slug: "laval-virtual-europe-2021",
    role: "Speaker + Panelist",
    title: "The Rise of Virtual Architecture",
    org: "Laval Virtual Europe",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Virtual (Laval, France)",
    url: "https://youtu.be/9NDVXdQgWuc",
  },
  {
    slug: "aia-convention-2021",
    role: "Speaker",
    title: "Experiential Design: The Future of Architecture",
    org: "AIA Convention",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Virtual",
    url: "https://aiafla.org/2021-convention_schedule.cfm",
  },
  {
    slug: "aixr-insights-live-2021",
    role: "Host",
    title: "Going Digital: Pivoting Live Events to Virtual Experiences",
    org: "AIXR Insights Live",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Virtual",
    url: "http://web.archive.org/web/20250908181200/https://aixr.org/event-listing/aixr-insights-live-going-digital-pivoting-live-events-to-virtual-experiences/",
  },
  {
    slug: "vivecon-2021",
    role: "Speaker",
    title: "Dev-ing Into Vive Focus 3",
    org: "ViveCon 2021 — Developer Track",
    date: "2021",
    endsISO: "2021-05-30T00:00:00Z",
    location: "Virtual",
    url: "https://youtu.be/qnqlweu0odo",
  },
  {
    slug: "syracuse-arch-guest-critic-2021",
    role: "Guest Critic",
    title: "Impending Certainties Studio Final",
    org: "Syracuse Architecture",
    date: "2021",
    endsISO: "2021-05-30T00:00:00Z",
    location: "Syracuse, NY",
  },
  {
    slug: "nyu-itp-guest-critic-2021",
    role: "Guest Critic",
    title: "VR Thesis Finals",
    org: "NYU ITP",
    date: "2021",
    endsISO: "2021-05-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "columbia-arch-guest-critic-2021",
    role: "Guest Critic",
    title: "Virtual Architecture Studio Final",
    org: "Columbia Architecture",
    date: "2021",
    endsISO: "2021-05-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "realtime-conference-2021-host",
    role: "Host + Curator + Speaker",
    title: "Social VR, NFTs, & Virtual Worlds: Architecture's New Domain? (with Kim Baumann Larsen)",
    org: "RealTime Conference — Architecture Track",
    date: "2021",
    endsISO: "2021-04-26T00:00:00Z",
    location: "Virtual",
  },
  {
    slug: "nyu-steinhardt-2021",
    role: "Guest Lecturer",
    title: "Business of Virtual Reality and Augmented Reality",
    org: "NYU Steinhardt",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "5th-wall-forum-reveal-2021",
    role: "Co-Host",
    title: "Reveal",
    org: "5th Wall Forum",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Virtual",
  },
  {
    slug: "vienna-civa-festival-2021",
    role: "Instructor",
    title: "UE4 Instructor",
    org: "Vienna CIVA Festival",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Vienna, Austria",
  },
  {
    slug: "nyvr-art-in-vr-2021",
    role: "Speaker",
    title: "NYVR Art in VR",
    org: "NYVR",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "New York, NY",
    url: "https://www.youtube.com/watch?v=KmldJP0H2n8",
  },
  {
    slug: "somnium-vr-fireside-2021",
    role: "Panelist",
    title: "Somnium VR Architecture Fireside Chat",
    org: "Somnium Space",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Virtual",
    url: "https://www.twitch.tv/videos/882667488",
  },
  {
    slug: "vrar-chicago-2021",
    role: "Panelist",
    title: "The Next Evolution in Art & Culture",
    org: "VRAR Chicago",
    date: "2021",
    endsISO: "2021-06-30T00:00:00Z",
    location: "Chicago, IL",
    url: "https://www.facebook.com/1306576549408541/videos/239225757778133",
  },
  {
    slug: "seoul-performing-arts-2022",
    role: "Keynote Speaker",
    title: "Performing in the Metaverse (메타버스에서 공연하기)",
    org: "Art Lab x Seoul Performing Arts Festival",
    date: "Oct 2022",
    endsISO: "2022-10-30T00:00:00Z",
    location: "Seoul, South Korea",
    url: "https://web.archive.org/web/20221202000431/https://www.gokams.or.kr/webzine/wNew/column/column_view.asp?idx=2596&page=1&c_idx=95&searchString=&c_idx_2=",
  },
  {
    slug: "unreal-fest-2022-new-orleans",
    role: "Speaker",
    title: "Virtual Reality and OpenXR in UE5",
    org: "Unreal Fest",
    date: "2022",
    endsISO: "2022-10-30T00:00:00Z",
    location: "New Orleans, LA",
    url: "https://www.youtube.com/watch?v=JD95BklloHk",
  },
  {
    slug: "siggraph-2022",
    role: "Art Paper Speaker + NVIDIA Featured Speaker",
    title: "A Tale of Two Productions: A Christmas Carol On Stage and in Virtual Reality",
    org: "SIGGRAPH",
    date: "2022",
    endsISO: "2022-08-15T00:00:00Z",
    location: "Vancouver, Canada",
    url: "https://www.nvidia.com/en-us/on-demand/session/siggraph2022-sigg22-s-18/",
  },
  {
    slug: "broadway-tech-accelerator-2022",
    role: "Speaker",
    title: "Broadway Tech Accelerator",
    org: "Broadway Tech Accelerator",
    date: "2022",
    endsISO: "2022-06-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "cornell-guest-lecture-2022",
    role: "Guest Lecturer",
    title: "Cornell University",
    org: "Cornell University",
    date: "2022",
    endsISO: "2022-06-30T00:00:00Z",
    location: "Ithaca, NY",
  },
  {
    slug: "awe-2022-xr-boot-camp",
    role: "Workshop",
    title: "Building a Live Show from Scratch: XR Boot Camp w/ Heavenue",
    org: "AWE USA 2022",
    date: "2022",
    endsISO: "2022-06-01T00:00:00Z",
    location: "Santa Clara, CA",
    url: "https://youtu.be/BWxtAOM_I8Y",
  },
  {
    slug: "korean-natl-univ-arts-2022",
    role: "Guest Lecturer",
    title: "Korean National University of Arts / Pohang Tech University",
    org: "Korean National University of Arts",
    date: "2022",
    endsISO: "2022-06-30T00:00:00Z",
    location: "Seoul, South Korea",
  },
  {
    slug: "gdc-2022-live-vr-actors",
    role: "Speaker",
    title: "Up Close & Virtual: The Power of Live VR Actors — Future Realities Summit",
    org: "GDC",
    date: "2022",
    endsISO: "2022-03-25T00:00:00Z",
    location: "San Francisco, CA",
    url: "https://schedule.gdconf.com/session/future-realities-summit-up-close-virtual-the-power-of-live-vr-actors/884641",
  },
  {
    slug: "usitt-2022",
    role: "Speaker + Panelist",
    title: "Game Engines in Performance Design, Film Production, and Architecture",
    org: "USITT",
    date: "Mar 5, 2022",
    endsISO: "2022-03-05T23:00:00Z",
    location: "Fort Lauderdale, FL",
    url: "https://s7.goeshow.com/usitt/annual/2022/Conference_Schedule.cfm?session_key=F95C7FBA-90B1-1C06-DFD2-AB9DB72A6D5D",
  },
  {
    slug: "nyu-tisch-guest-2022",
    role: "Guest Lecturer",
    title: "NYU Tisch",
    org: "NYU Tisch",
    date: "2022",
    endsISO: "2022-06-30T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "chapman-university-2022",
    role: "Guest Lecturer",
    title: "Chapman University",
    org: "Chapman University",
    date: "2022",
    endsISO: "2022-06-30T00:00:00Z",
    location: "Orange, CA",
  },
  {
    slug: "sxsw-2023-xr-live-events",
    role: "Panelist",
    title: "Is This Really Live? Performance In The Age Of XR",
    org: "SXSW",
    date: "Mar 2023",
    endsISO: "2023-03-15T00:00:00Z",
    location: "Austin, TX",
    url: "https://schedule.sxsw.com/2023/events/PP129926",
  },
  {
    slug: "nvidia-vcr-2023",
    role: "Speaker",
    title: "VCR: Easily Record and Playback Your VR",
    org: "NVIDIA",
    date: "Feb 2023",
    endsISO: "2023-02-28T00:00:00Z",
    location: "Virtual",
    url: "https://www.linkedin.com/posts/alexcoulombe_nvidia-vcr-easily-record-and-playback-your-activity-7028396545557299200-2iQI",
  },
  {
    slug: "nyvr-2023",
    role: "Speaker",
    title: "Agile Lens Update",
    org: "NYVR",
    date: "Jun 2023",
    endsISO: "2023-06-15T00:00:00Z",
    location: "New York, NY",
    url: "https://youtu.be/7GH-bPLj_NM",
  },
  {
    slug: "vrto-2023",
    role: "Speaker",
    title: "Bringing MetaHumans to Life: Achieving Powerful Impact with Enterprise VR Storytelling",
    org: "VRTO",
    date: "Jul 2023",
    endsISO: "2023-07-15T00:00:00Z",
    location: "Toronto, Canada",
    url: "https://conference.virtualreality.to/schedule-vrto-2023/",
  },
  {
    slug: "digital-fashion-week-2023",
    role: "Speaker",
    title: "Unity3D to Unreal Engine",
    org: "Digital Fashion Week",
    date: "Sep 2023",
    endsISO: "2023-09-15T00:00:00Z",
    location: "New York, NY",
    url: "https://www.youtube.com/watch?v=H9cN0m-p8zM",
  },
  {
    slug: "unreal-fest-2023-metahuman",
    role: "Speaker",
    title: "Diving Deep with MetaHuman Animator, Four Seasons Lake Austin VR Showroom",
    org: "Unreal Fest",
    date: "Oct 2023",
    endsISO: "2023-10-15T00:00:00Z",
    location: "Seattle, WA",
    url: "https://www.youtube.com/watch?v=6la2yieiCG0",
  },
  {
    slug: "ubc-guest-speaker-2023",
    role: "Guest Speaker",
    title: "How to Run an XR Creative Studio",
    org: "University of British Columbia",
    date: "Nov 2023",
    endsISO: "2023-11-15T00:00:00Z",
    location: "Vancouver, Canada",
  },
  {
    slug: "sva-2023",
    role: "Speaker",
    title: "Limits are Your Medium",
    org: "School of Visual Arts",
    date: "Dec 2023",
    endsISO: "2023-12-15T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "worlds-in-play-2024",
    role: "Speaker",
    title: "LINE! How Olde Theatre Traditions Make New Innovations",
    org: "Worlds in Play",
    date: "Jan 2024",
    endsISO: "2024-01-31T00:00:00Z",
    location: "Chicago, IL",
    url: "https://worldsinplay.com/past-events-1",
  },
  {
    slug: "unreal-fest-gold-coast-2024",
    role: "Speaker",
    title: "Unreal Fest Gold Coast",
    org: "Unreal Fest",
    date: "May 29–30, 2024",
    endsISO: "2024-05-30T23:00:00Z",
    location: "Gold Coast, Australia",
  },
  {
    slug: "unreal-fest-prague-2024",
    role: "Speaker",
    title: "I Wish I Learned This Sooner!",
    org: "Unreal Fest Prague",
    date: "Jun 18–20, 2024",
    endsISO: "2024-06-20T23:00:00Z",
    location: "Prague, Czech Republic",
    url: "https://www.youtube.com/watch?v=m0T8euG9Rh8",
  },
  {
    slug: "svvr-connect-2024",
    role: "Speaker",
    title: "How to Build a 5000 sq ft VR Showroom",
    org: "SVVR Connect",
    date: "Sep 2024",
    endsISO: "2024-09-15T00:00:00Z",
    location: "Santa Clara, CA",
    url: "https://youtu.be/9q7GIQVh2Nc",
  },
  {
    slug: "unreal-fest-seattle-2024",
    role: "Speaker",
    title: "Intro to the Variant Manager and Configurator Templates; Mind The Gap: Transitioning from Unity to Unreal Engine; Intro to Augmented Reality",
    org: "Unreal Fest Seattle",
    date: "Oct 2024",
    endsISO: "2024-10-15T00:00:00Z",
    location: "Seattle, WA",
    url: "https://youtu.be/OWwPUlGJr8k",
  },
  {
    slug: "unreal-day-belgrade-2024",
    role: "Speaker",
    title: "From Meta Quest to Apple Vision Pro and Beyond; How to Build a 5000 sq ft UE5 VR Showroom",
    org: "Unreal Day Belgrade",
    date: "Oct 2024",
    endsISO: "2024-10-20T00:00:00Z",
    location: "Belgrade, Serbia",
    url: "https://youtu.be/9q7GIQVh2Nc",
  },
  {
    slug: "digital-body-festival-2024",
    role: "Speaker",
    title: "Directing AI Performers: New Methodologies from Human-Non-Human Collaboration",
    org: "Digital Body Festival",
    date: "Nov 2024",
    endsISO: "2024-11-15T00:00:00Z",
    location: "New York, NY",
  },
  {
    slug: "raindance-immersive-2025",
    role: "Official Selection",
    title: "A Christmas Carol VR — Finalist, Best Immersive Theatre",
    org: "Raindance Immersive",
    date: "2025",
    endsISO: "2025-10-15T00:00:00Z",
    location: "London, UK / Virtual",
    url: "https://www.raindanceimmersive.com/2025-a-christmas-carol/",
  },
  {
    slug: "siggraph-2025-paper",
    role: "Paper Author",
    title: "Seeing Yourself on Stage: Multi-Avatar Performance and the Evolution of Self-Monitoring in VR",
    org: "SIGGRAPH",
    date: "Aug 2025",
    endsISO: "2025-08-15T00:00:00Z",
    location: "Vancouver, Canada",
    url: "https://dl.acm.org/doi/10.1145/3721244.3742445",
  },
  {
    slug: "unreal-fest-orlando-2025",
    role: "Speaker",
    title: "The Best Template You're Not Using: Maximizing the Collab Viewer",
    org: "Unreal Fest Orlando",
    date: "2025",
    endsISO: "2025-09-30T00:00:00Z",
    location: "Orlando, FL",
    url: "https://www.youtube.com/watch?v=Gy6_v9jr-5w",
  },
  {
    slug: "unreal-fest-stockholm-2025",
    role: "Speaker",
    title: "I Wish I Learned This Sooner! — Part 2",
    org: "Unreal Fest Stockholm",
    date: "2025",
    endsISO: "2025-11-15T00:00:00Z",
    location: "Stockholm, Sweden",
    url: "https://www.youtube.com/watch?v=M1J25jJ79U8",
  },
  {
    slug: "harvardxr-2026-keynote",
    role: "Closing Keynote",
    title: "10 Lessons from 10 Years of Running an XR Enterprise Studio",
    org: "HarvardXR",
    date: "Apr 17, 2026",
    endsISO: "2026-04-17T23:00:00Z",
    location: "Cambridge, MA (Harvard University)",
    url: "https://www.harvardxr.com/2026/program-2026",
  },
  {
    slug: "fmx-2026",
    role: "Speaker",
    title: "Staging the Metaverse: Scaling Virtual Productions & Performances with Unreal Engine",
    org: "FMX 2026 (with David Gochfeld)",
    date: "Thu May 7, 2026",
    endsISO: "2026-05-07T22:00:00Z",
    location: "Stuttgart, Germany",
    url: "https://fmx.de/en/news/latest-news/news-06-05-2026",
  },
  {
    slug: "nxt-bld-2026",
    role: "Speaker",
    title: "Productizing XR for Architecture (with Yu-Jun Yeh)",
    org: "NXT BLD — 10th Anniversary",
    date: "May 13, 2026",
    endsISO: "2026-05-13T22:00:00Z",
    location: "QEII Centre, London",
    url: "https://nxtaec.com/video/productizing-xr-for-architecture-alex-coulombe-yu-jun-yeh-agile-lens/",
  },
  {
    slug: "pmre-2026-keynote",
    role: "Keynote Speaker",
    title: "Architect to XR-chitect: The Best Career Advice I Ever Ignored",
    org: "PMRE 2026 — Photo + Media for Real Estate Conference",
    date: "Nov 17–19, 2026",
    endsISO: "2026-11-20T06:00:00Z",
    location: "Palms Casino Resort, Las Vegas",
    url: "https://pmreconference.com/agenda",
  },
  {
    slug: "worlds-in-action-hack-la",
    role: "Judge + Mentor",
    title: "Worlds in Action Hack [02-LA]",
    org: "Sensai, with World Labs, PICO, and SIGGRAPH 2026",
    date: "Jul 18–19, 2026",
    endsISO: "2026-07-20T04:00:00Z",
    location: "MG Studio, Los Angeles",
    url: "https://sensaihack.com/worldsinaction-2-la/",
    image: "/worlds-in-action-hack.jpg",
  },
  {
    slug: "siggraph-2026-stage-presence",
    role: "Speaker",
    title: "Stage Presence: Design and Testing of a Virtual Rehearsal Room Toolset",
    org: "SIGGRAPH 2026",
    date: "Sun Jul 19, 4:25–4:45pm PT",
    endsISO: "2026-07-19T23:45:00Z",
    location: "Room 403 B, Los Angeles",
    url: "https://s2026.conference-schedule.org/presenter/?uid=645453",
  },
  {
    slug: "siggraph-2026-gaussian-splats",
    role: "Instructor",
    title: "Powered by Gaussian Splats: From World Models to 3D Interactive Worlds",
    org: "SIGGRAPH 2026 — Hands-on Course",
    date: "Mon Jul 20, 3:30–5:00pm PT",
    endsISO: "2026-07-21T00:00:00Z",
    location: "Concourse Hall, Los Angeles",
    url: "https://s2026.conference-schedule.org/presenter/?uid=645453",
  },
  {
    slug: "siggraph-2026-virtual-theatre",
    role: "Panelist",
    title: "Virtual Theatre: Producing Live Theatre on Virtual Stages",
    org: "SIGGRAPH 2026",
    date: "Wed Jul 22, 1:00–1:45pm PT",
    endsISO: "2026-07-22T20:45:00Z",
    location: "Concourse Hall, Los Angeles",
    url: "https://s2026.conference-schedule.org/presenter/?uid=645453",
  },
];
