// GENERATED by scripts/audit-hero-links.mjs — do not edit by hand.
//
// Links that render somewhere on the site but are not reachable from the
// data modules lib/heroLinkPool.ts reads (they live in page JSX). Labels are
// the anchor text the site itself shows. Regenerate with:
//
//   npm run build && npm run gen:hero-links

import type { HeroLink } from "@/lib/heroLinks";

export const generatedHeroLinks: HeroLink[] = [
  {
    "href": "/account",
    "label": "My Account",
    "kicker": "On this site · /account",
    "tier": "section"
  },
  {
    "href": "/lab/fabel-showcase/devlog#round-two",
    "label": "Read the round-two devlog",
    "kicker": "On this site · /lab/fabel-showcase/devlo…",
    "tier": "deep"
  },
  {
    "href": "/lab/video-qa-workbench/beta-handbook",
    "label": "Read the tester handbook",
    "kicker": "On this site · /lab/video-qa-workbench/b…",
    "tier": "deep"
  },
  {
    "href": "/lab/video-qa-workbench/field-guide",
    "label": "Beta field guide",
    "kicker": "On this site · /lab/video-qa-workbench/f…",
    "tier": "deep"
  },
  {
    "href": "http://alexcoulombe.com",
    "label": "Visit anyway (brave)",
    "kicker": "alexcoulombe.com",
    "tier": "external"
  },
  {
    "href": "https://agilelens.com",
    "label": "Agile Lens",
    "kicker": "agilelens.com",
    "tier": "external"
  },
  {
    "href": "https://agilelens.com/contact",
    "label": "agilelens.com/contact",
    "kicker": "agilelens.com",
    "tier": "external"
  },
  {
    "href": "https://agilelens.com/portfolio",
    "label": "Hire the studio Agile Lens builds this…",
    "kicker": "agilelens.com",
    "tier": "external"
  },
  {
    "href": "https://agilelens.com/unrealnyc",
    "label": "Unreal NYC",
    "kicker": "agilelens.com",
    "tier": "external"
  },
  {
    "href": "https://alexcoulombe.com",
    "label": "Alex Coulombe",
    "kicker": "alexcoulombe.com",
    "tier": "external"
  },
  {
    "href": "https://apps.apple.com/us/app/a-christmas-carol-vr-teaser/id6738833389",
    "label": "Apple Vision Pro",
    "kicker": "apps.apple.com",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/product/app-store-aso",
    "label": "Get it on Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/product/interview-coach-pro",
    "label": "Get it on Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/product/ios-testflight",
    "label": "Get it on Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/product/metahuman-godot-pipeline",
    "label": "Get it on Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/product/spatial-deck-maker",
    "label": "Get it on Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/product/ue5-testflight",
    "label": "Get it on Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://capafy.ai/publisher/alex-coulombe-presents",
    "label": "Capafy",
    "kicker": "capafy.ai",
    "tier": "external"
  },
  {
    "href": "https://communities.unrealengine.com/new-york",
    "label": "Official Epic community page",
    "kicker": "communities.unrealengine.com",
    "tier": "external"
  },
  {
    "href": "https://credential.unrealengine.com/2e350d0f-ee6d-4239-a596-975ff749d550#acc.H86EwZ9F",
    "label": "credential.unrealengine.com",
    "kicker": "credential.unrealengine.com",
    "tier": "external"
  },
  {
    "href": "https://credential.unrealengine.com/ae75c735-f7c6-4fc5-a633-f400ec2efd4b#acc.Mpe8GrAh",
    "label": "credential.unrealengine.com",
    "kicker": "credential.unrealengine.com",
    "tier": "external"
  },
  {
    "href": "https://discord.gg/bNh4aqSEg",
    "label": "Unreal NYC Training Discord",
    "kicker": "discord.gg",
    "tier": "external"
  },
  {
    "href": "https://github.com/BenLumenDigital/VisionOS-SimHands",
    "label": "VisionOS‑SimHands",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/BerriAI/litellm",
    "label": "LiteLLM Proxy",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/Clancey/godot/tree/visionos_master_pr",
    "label": "Clancey/godot",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/godotengine/godot/pull/109975",
    "label": "PR #109975",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews",
    "label": "GitHub",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/MetaHumanGodot/blob/main/CHANGELOG.md",
    "label": "CHANGELOG.md",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/MetaHumanGodot/releases",
    "label": "Releases",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Audience-Mode",
    "label": "Audience Mode",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Author-Guide",
    "label": "Author's Guide",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Bundled-Plays",
    "label": "The Bundled Plays",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Camera-and-Film-Mode",
    "label": "Camera & Film Mode",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/DMX-Lighting",
    "label": "DMX Lighting Boards",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Director-Guide",
    "label": "Director's Guide",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Glossary",
    "label": "Glossary",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Multiple-Devices",
    "label": "Connecting Multiple Devices",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Performer-Guide",
    "label": "Performer's Guide",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/QLab-and-OSC",
    "label": "Showrunning with QLab (OSC)",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Quick-Start",
    "label": "Quick Start",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Room-Scanning",
    "label": "Room Scanning (LiDAR)",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/Understudy/wiki/Troubleshooting",
    "label": "Troubleshooting",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/blueprint-auto-layout/issues",
    "label": "Report an issue",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/blueprint-auto-layout/releases/latest",
    "label": "Latest release",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/claude-fleet/wiki/Architecture",
    "label": "Architecture",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/claude-fleet/wiki/Configuration-Reference",
    "label": "Configuration Reference",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/claude-fleet/wiki/FAQ",
    "label": "FAQ",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/claude-fleet/wiki/Getting-Started",
    "label": "Getting Started",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/claude-fleet/wiki/Recipes",
    "label": "Recipes",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/godot-avp-cascade/wiki/Architecture",
    "label": "How the Game Is Built",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/godot-avp-cascade/wiki/Build-and-Deploy",
    "label": "Build and Deploy",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/godot-avp-cascade/wiki/Getting-Started",
    "label": "Getting Started",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/godot-avp-cascade/wiki/Hand-Tracking",
    "label": "Hand Tracking, Explained",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/godot-avp-cascade/wiki/Procedural-Audio",
    "label": "Procedural Audio",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/godot-avp-cascade/wiki/visionOS-Gotchas",
    "label": "visionOS Gotchas",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/Adding-a-Scene",
    "label": "Adding a Scene",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/Architecture#carol-scene",
    "label": "A Christmas Carol — Stave 1",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/Architecture#dnd-scene",
    "label": "Stage Presence — D&D Encounter",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/Architecture#four-seasons-scene",
    "label": "Four Seasons Lake Austin",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/Architecture",
    "label": "Architecture",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/FAQ",
    "label": "FAQ",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/For-Talk-Presenters",
    "label": "For Talk Presenters",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/holodeck-pocket/wiki/Models-and-Licenses",
    "label": "Models and Licenses",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/AI-Workflow",
    "label": "09 · AI Workflow",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Animations",
    "label": "07 · Animations",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Content-Authoring",
    "label": "02 · Content Authoring",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Getting-Started",
    "label": "Getting Started",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Import-and-Export-Tools",
    "label": "08 · Import & Export Tools",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Keyboard-Shortcuts",
    "label": "10 · Keyboard Shortcuts",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Media",
    "label": "03 · Media",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Move-Mode-and-Layout",
    "label": "04 · Move Mode & Layout",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Presenter-Tools",
    "label": "06 · Presenter Tools",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Theme-and-Settings",
    "label": "05 · Theme & Settings",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/spatial-deck/wiki/Troubleshooting",
    "label": "11 · Troubleshooting",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/ibrews/unreal-custodian/blob/main/ROADMAP.md",
    "label": "ROADMAP.md",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://github.com/nocxr",
    "label": "Marshall's (@nocxr)",
    "kicker": "github.com",
    "tier": "external"
  },
  {
    "href": "https://godotengine.org/",
    "label": "Godot",
    "kicker": "godotengine.org",
    "tier": "external"
  },
  {
    "href": "https://ibrews.gumroad.com",
    "label": "Gumroad",
    "kicker": "ibrews.gumroad.com",
    "tier": "external"
  },
  {
    "href": "https://instagram.com/alexctraining",
    "label": "Instagram",
    "kicker": "instagram.com",
    "tier": "external"
  },
  {
    "href": "https://linkedin.com/in/alexcoulombe",
    "label": "LinkedIn",
    "kicker": "linkedin.com",
    "tier": "external"
  },
  {
    "href": "https://linktr.ee/unoffunrealpod",
    "label": "UE Podcast",
    "kicker": "linktr.ee",
    "tier": "external"
  },
  {
    "href": "https://twitter.com/alexctraining",
    "label": "X — UE Tips",
    "kicker": "twitter.com",
    "tier": "external"
  },
  {
    "href": "https://twitter.com/ibrews",
    "label": "X / @ibrews",
    "kicker": "twitter.com",
    "tier": "external"
  },
  {
    "href": "https://uepodcast.com",
    "label": "The (Unofficial) Unreal Engine Podcast",
    "kicker": "uepodcast.com",
    "tier": "external"
  },
  {
    "href": "https://us06web.zoom.us/meeting/register/BpUpfAPDToWFUyqRgPFwXA",
    "label": "Reserve a free seat",
    "kicker": "us06web.zoom.us",
    "tier": "external"
  },
  {
    "href": "https://web.archive.org/web/2013/http://alexcoulombe.com",
    "label": "Wayback Machine (recommended)",
    "kicker": "web.archive.org",
    "tier": "external"
  },
  {
    "href": "https://web.archive.org/web/20221202000431/https://www.gokams.or.kr/webzine/wNew/column/column_view.asp?idx=2596&amp;page=1&amp;c_idx=95&amp;searchString=&amp;c_idx_2=",
    "label": "Keynote Speaker Performing in the Metaverse…",
    "kicker": "web.archive.org",
    "tier": "external"
  },
  {
    "href": "https://www.5thwallforum.com/team",
    "label": "5th Wall Forum Founding Advisory Board —…",
    "kicker": "5thwallforum.com",
    "tier": "external"
  },
  {
    "href": "https://www.agilelens.com",
    "label": "Agile Lens",
    "kicker": "agilelens.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com",
    "label": "Alex Coulombe Presents",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com/lab",
    "label": "the Lab",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com/lab/xrsim",
    "label": "xrsim",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com/members",
    "label": "membership",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com/training#calendar",
    "label": "training",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com/training/#poll",
    "label": "training",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.alexcoulombepresents.com/vote",
    "label": "Vote for what's next",
    "kicker": "alexcoulombepresents.com",
    "tier": "external"
  },
  {
    "href": "https://www.isleworlds.com/",
    "label": "Isle Founding Advisor. Real-world,…",
    "kicker": "isleworlds.com",
    "tier": "external"
  },
  {
    "href": "https://www.linkedin.com/company/alexctraining",
    "label": "LinkedIn",
    "kicker": "linkedin.com",
    "tier": "external"
  },
  {
    "href": "https://www.linkedin.com/posts/alexcoulombe_long-overdue-europe-post-1-of-2-this-activity-7464479226625265665-d8dF",
    "label": "Recent: the Europe tour recap (FMX + NXT…",
    "kicker": "linkedin.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDco-vxai_cyhnQII_sys5DI",
    "label": "playlist VR Talks, Tests & Tutorials The…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDd2EaCeOBMNUg_RdOmXdif7",
    "label": "playlist MetaHuman Animator Digital humans,…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDe4m8PcrNBgv5_DWJTWsbJ2",
    "label": "playlist The (Unofficial) Unreal Engine…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDeGHS1mW8p1LPfL0aPisjWN",
    "label": "playlist Pixel Streaming Stuff! Unreal in…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDemC1EPbDIyKhkXu5gPGWFN",
    "label": "All 46 talks on YouTube",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDeo1g9OnZSSDLJsKk8iOTPg",
    "label": "playlist Introducing Stage Presence The…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDf7JV8iJM2kV-n3zAP6mIZ7",
    "label": "playlist A Christmas Carol VR The annual…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/playlist?list=PLBHPEwkDnRDfa4kxE7u4idWvBkbHoEkk-",
    "label": "playlist Alex Vision Pro Every Apple Vision…",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/watch?v=FW6xfFzF0_o",
    "label": "watch?v=FW6xfFzF0 o",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://www.youtube.com/watch?v=JR5397NUz3I",
    "label": "SensAI",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://x.com/GrhmRst/status/2086611827471896927",
    "label": "Thanks for the 92.4 gig 🫡 @ GrhmRst · Aug…",
    "kicker": "x.com",
    "tier": "external"
  },
  {
    "href": "https://x.com/SupersaneG/status/2086959483373179070",
    "label": "550 gb on main box, 1.2 tb on server. Thank…",
    "kicker": "x.com",
    "tier": "external"
  },
  {
    "href": "https://x.com/alexctraining",
    "label": "X (daily #uetips!)",
    "kicker": "x.com",
    "tier": "external"
  },
  {
    "href": "https://youtube.com/@ibrews",
    "label": "YouTube",
    "kicker": "youtube.com",
    "tier": "external"
  },
  {
    "href": "https://youtube.com/@ibrews?sub_confirmation=1",
    "label": "Subscribe on YouTube",
    "kicker": "youtube.com",
    "tier": "external"
  }
];
