import type { CardCategory } from "@/lib/categories";

// ── Press & media mentions ───────────────────────────────────────────────
//
// Distinct from lib/appearances.ts: these are pieces of coverage, not
// engagements he showed up for. `kind` drives the same color-coded legend
// as the appearances side — "Press" (article/interview), "Podcast", or
// "Work Featured" (his work shows up — a rendering, a project, a review —
// without him personally being interviewed or named).
//
// Sourced from ~/knowledge/media/youtube/press-mentions.md (itself pulled
// from the agilelens.com/media Wayback Machine snapshot) plus direct links
// Alex supplied. `url` omitted only when no source ever cited one.

export type PressMention = {
  slug: string;
  kind: Extract<CardCategory, "Press" | "Podcast" | "Work Featured">;
  outlet: string;
  title: string;
  date: string;
  dateISO: string;
  url?: string;
};

export const pressMentions: PressMention[] = [
  {
    slug: "fractured-atlas-2015",
    kind: "Press",
    outlet: "Fractured Atlas",
    title: "The New Artist's Medium: Getting Started with Virtual Reality",
    date: "2015",
    dateISO: "2015-06-15T00:00:00Z",
    url: "https://blog.fracturedatlas.org/the-new-artist-s-medium-getting-started-with-virtual-reality-19f24b95c4e7",
  },
  {
    slug: "vr-scout-vive-tracker-2017",
    kind: "Work Featured",
    outlet: "VR Scout",
    title: "Developer Uses Vive Tracker to Battle Ceiling Fan",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "https://vrscout.com/news/developer-vive-tracker-battle-ceiling-fan/",
  },
  {
    slug: "what-is-vr-book-2017",
    kind: "Press",
    outlet: "What is VR? (book)",
    title: "Contributed chapter",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "http://whatisvrbook.com/",
  },
  {
    slug: "uploadvr-vive-tracker-2017",
    kind: "Work Featured",
    outlet: "UploadVR",
    title: "HTC's Vive Tracker Has Brought Out The Best In VR Innovation",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "https://uploadvr.com/vive-tracker-vr-innovation/",
  },
  {
    slug: "ibm-thinkleaders-2017",
    kind: "Press",
    outlet: "IBM ThinkLeaders",
    title: "Designing like you're there: What I learned using VR for architecture",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "https://www.ibm.com/blogs/insights-on-business/ibmix/designing-like-youre-learned-using-vr-architecture/",
  },
  {
    slug: "oregon-arts-watch-2017",
    kind: "Press",
    outlet: "Oregon Arts Watch",
    title: "Theater at the Intersection",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "http://www.orartswatch.org/theater-at-the-intersection/",
  },
  {
    slug: "sketchfab-webvr-hackathon-2017",
    kind: "Work Featured",
    outlet: "Sketchfab",
    title: "Sketchfab Hosts WebVR Hackathon — 2nd place finish",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "https://blog.sketchfab.com/sketchfab-hosts-webvr-hackathon/",
  },
  {
    slug: "lighting-sound-america-2017",
    kind: "Press",
    outlet: "Lighting & Sound America",
    title: "Opening the Door to Virtual Reality",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "http://www.lightingandsoundamerica.com/reprint/AgileLens.pdf",
  },
  {
    slug: "the-game-crafter-big-box-2017",
    kind: "Work Featured",
    outlet: "The Game Crafter",
    title: "Alex Coulombe Selects Winner of Big Box Challenge",
    date: "2017",
    dateISO: "2017-06-15T00:00:00Z",
    url: "http://news.thegamecrafter.com/post/166221033051/big-box-challenge-winner-faza",
  },
  {
    slug: "sketchbox-2018",
    kind: "Press",
    outlet: "Sketchbox",
    title: "Designing VR: Alex Coulombe from Agile Lens",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://blog.sketchbox3d.com/designing-vr-alex-coulombe-from-agile-lens-73de9c925d6a",
  },
  {
    slug: "engadget-intel-vr-2018",
    kind: "Work Featured",
    outlet: "Engadget",
    title: "Intel is funding the future of large-scale VR environments",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://www.engadget.com/2018/03/06/intel-is-funding-the-future-of-large-scale-vr-environments/",
  },
  {
    // Two press-mentions.md lines ("Im-Arch" and "Fabio Palvelli") both cite
    // the identical title "Talking VR with Alex Coulombe" — the YouTube
    // video's real channel (confirmed via oEmbed) is Fabio Palvelli, who
    // conducted this interview for Im-Arch. Same underlying interview,
    // merged rather than double-counted.
    slug: "im-arch-talking-vr-2018",
    kind: "Podcast",
    outlet: "Im-Arch (interview by Fabio Palvelli)",
    title: "Talking VR with Alex Coulombe",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://www.youtube.com/watch?v=7nWJqMw-v5Q",
  },
  {
    slug: "cgarchitect-3d-awards-judge-2018",
    kind: "Press",
    outlet: "CGarchitect 3D Awards",
    title: "Judge",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
  },
  {
    slug: "that-bim-girl-2018",
    kind: "Podcast",
    outlet: "That BIM Girl",
    title: "Taking VR to the Next Level with Alex Coulombe",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://www.youtube.com/watch?v=S1GOsbEXfy4",
  },
  {
    slug: "cg-garage-chris-nichols-2018",
    kind: "Podcast",
    outlet: "CG Garage",
    title: "Interview with Chris Nichols",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://www.chaosgroup.com/blog/alex-coulombe-agile-lens",
  },
  {
    slug: "unreal-engine-designing-in-vr-2018",
    kind: "Press",
    outlet: "Unreal Engine",
    title: "Designing in VR: Agile Lens helps furnish a theater with Unreal Engine",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://www.unrealengine.com/en-US/blog/designing-in-vr-agile-lens-helps-furnish-a-theater-with-unreal-engine",
  },
  {
    slug: "vr-voice-leapcon-2018",
    kind: "Podcast",
    outlet: "VR Voice",
    title: "What I Learned at LeapCon — In the VR Voice Hot Seat",
    date: "2018",
    dateISO: "2018-06-15T00:00:00Z",
    url: "https://www.crowdcast.io/e/in-the-vr-voice-hot-seat-with-alex-coulombe-creative-director-agile-lens",
  },
  {
    slug: "too-hip-podcast-2019",
    kind: "Podcast",
    outlet: "TOO HIP",
    title: "Episode 003 — Alex Coulombe: VR Ninja!",
    date: "2019",
    dateISO: "2019-06-15T00:00:00Z",
    url: "http://toohippodcast.com/post/182220561187/episode-003-with-alex-coulombe-vr-ninja",
  },
  {
    slug: "caledonian-record-2019",
    kind: "Press",
    outlet: "Caledonian Record",
    title: "The Future Is Now: SJA Alum Offers Glimpse Into Virtual Reality",
    date: "2019",
    dateISO: "2019-06-15T00:00:00Z",
    url: "https://www.caledonianrecord.com/news/local/the-future-is-now-sja-alum-offers-glimpse-into-virtual/article_a112e4ba-cb68-50b9-9f1e-dc7c8fe5818e.html",
  },
  {
    slug: "ieee-avatar-selection-2019",
    kind: "Press",
    outlet: "IEEE",
    title: "Avatar Selection for Live Performance in Virtual Reality: A Case Study — Co-Author",
    date: "2019",
    dateISO: "2019-06-15T00:00:00Z",
    url: "https://ieeexplore.ieee.org/abstract/document/8811548",
  },
  {
    slug: "tap-into-film-judge-2019",
    kind: "Press",
    outlet: "Tap Into Film",
    title: "Film Judge",
    date: "2019",
    dateISO: "2019-06-15T00:00:00Z",
    url: "https://www.socapa.org/tapintofilm/",
  },
  {
    slug: "voices-of-vr-806-2019",
    kind: "Podcast",
    outlet: "Voices of VR",
    title: "#806 — Interdisciplinary Design at the Intersection of Theater & Architecture + Volumetric Capture Experiments",
    date: "2019",
    dateISO: "2019-06-15T00:00:00Z",
    url: "https://voicesofvr.com/806-interdisciplinary-design-at-the-intersection-of-theater-architecture-volumetric-capture-experiments/",
  },
  {
    slug: "ryan-schultz-loveseat-review-2019",
    kind: "Work Featured",
    outlet: "Ryan Schultz",
    title: "Loveseat Gives Us an Innovative Look at Theatre in Virtual Reality",
    date: "2019",
    dateISO: "2019-08-28T00:00:00Z",
    url: "https://ryanschultz.com/2019/08/28/review-loveseat-gives-us-a-innovative-look-at-theatre-in-virtual-reality/",
  },
  {
    slug: "no-proscenium-loveseat-2019",
    kind: "Work Featured",
    outlet: "No Proscenium",
    title: "Birds and Bees and Multiple Realities — 'Loveseat' at Venice VR",
    date: "2019",
    dateISO: "2019-08-15T00:00:00Z",
    url: "https://noproscenium.com/birds-and-bees-and-multiple-realities-loveseat-at-venice-vr-684c530c8ac7",
  },
  {
    slug: "seven-days-vt-2020",
    kind: "Press",
    outlet: "Seven Days VT",
    title: "New Head Stretchers Society Challenges Us to Learn New Things",
    date: "2020",
    dateISO: "2020-06-15T00:00:00Z",
    url: "https://www.sevendaysvt.com/vermont/new-head-stretchers-society-challenges-us-to-learn-new-things/Content?oid=29470354",
  },
  {
    slug: "theia-optim-2020",
    kind: "Press",
    outlet: "Theia Interactive",
    title: "Alex Coulombe Talks Unreal Engine Workflows",
    date: "Jan 2020",
    dateISO: "2020-01-22T00:00:00Z",
    url: "https://theia.io/2020/01/22/unreal-engine-workflow-interview-alex-coulombe/",
  },
  {
    slug: "yahoo-finance-realtime-conference-2020",
    kind: "Press",
    outlet: "Yahoo Finance",
    title: "RealTime Conference Kicks Off with Free Online Sessions",
    date: "2020",
    dateISO: "2020-04-15T00:00:00Z",
    url: "https://finance.yahoo.com/news/realtime-conference-kicks-off-free-174449615.html",
  },
  {
    slug: "currents-new-media-interview-2020",
    kind: "Podcast",
    outlet: "CURRENTS New Media",
    title: "Video Interview",
    date: "2020",
    dateISO: "2020-06-15T00:00:00Z",
    url: "https://currentsnewmedia.org/festivals/currents-new-media-2020/",
  },
  {
    slug: "alive-in-plasticland-tempest-2020",
    kind: "Press",
    outlet: "Alive in Plasticland",
    title: "Let's Dive Into The Under Presents' Tempest",
    date: "2020",
    dateISO: "2020-06-15T00:00:00Z",
    url: "https://medium.com/alive-in-plasticland/lets-dive-into-the-under-presents-tempest-pt-1-2d1ef2168c5f",
  },
  {
    slug: "jettison-documentary-2021",
    kind: "Work Featured",
    outlet: "Jettison",
    title: "Video Documentary",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://www.youtube.com/watch?v=9AH6nmpYSkE",
  },
  {
    slug: "ryan-schultz-25-people-2021",
    kind: "Press",
    outlet: "Ryan Schultz",
    title: "25 People in Social VR, Virtual Worlds, and the Metaverse Whom You Should Be Following",
    date: "Feb 2021",
    dateISO: "2021-02-18T00:00:00Z",
    url: "https://ryanschultz.com/2021/02/18/my-list-of-25-people-in-social-vr-virtual-worlds-and-the-metaverse-whom-you-should-be-following-plus-a-few-alternates/",
  },
  {
    slug: "aea-consulting-2021",
    kind: "Press",
    outlet: "AEA Consulting",
    title: "Construction After Covid: What's Next for Performing Arts Buildings?",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://aeaconsulting.com/insights/whats_next_for_performing_arts_infrastructure_projects",
  },
  {
    slug: "cg-garage-nfts-architecture-2021",
    kind: "Podcast",
    outlet: "CG Garage",
    title: "NFTs and Architecture (with Samuel Arsenault-Brassard)",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://www.chaosgroup.com/blog/samuel-arsenault-brassard-alex-coulombe-nfts-and-architecture",
  },
  {
    slug: "unreal-engine-meet-someone-unreal-2021",
    kind: "Press",
    outlet: "Unreal Engine",
    title: "Meet Someone Unreal: Alex Coulombe",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://www.instagram.com/p/CO0hyFcJYRT/",
  },
  {
    slug: "5th-wall-forum-podcast-2021",
    kind: "Podcast",
    outlet: "5th Wall Forum",
    title: "5th Wall Forum Podcast",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://podcasts.apple.com/us/podcast/5th-wall-forum/id1566627279",
  },
  {
    slug: "augmented-workforce-book-2021",
    kind: "Press",
    outlet: "The Augmented Workforce (book)",
    title: "Interviewee — Cathy Hackl & John Buzzell",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://smile.amazon.com/Augmented-Workforce-Artificial-Intelligence-Reality-ebook/dp/B094LL26BD",
  },
  {
    slug: "100-original-voices-xr-2021",
    kind: "Press",
    outlet: "Avi Bar-Zeev (Medium)",
    title: "100 Original Voices in XR",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://avibarzeev.medium.com/100-original-voices-in-xr-55b5a609f4ae",
  },
  {
    slug: "xrmust-interview-2021",
    kind: "Press",
    outlet: "XR Must",
    title: "Interview with Alex Coulombe",
    date: "2021",
    dateISO: "2021-06-15T00:00:00Z",
    url: "https://www.xrmust.com/xrmagazine/alex-coulombe-agile-lens/",
  },
  {
    slug: "no-proscenium-heavenue-2022",
    kind: "Podcast",
    outlet: "No Proscenium",
    title: "A Slice of Heavenue",
    date: "2022",
    dateISO: "2022-06-15T00:00:00Z",
    url: "https://noproscenium.com/podcast-a-slice-of-heavenue-2250f47397ff",
  },
  {
    slug: "unbuilt-interviews-2022",
    kind: "Podcast",
    outlet: "Unbuilt Interviews",
    title: "Unbuilt Interviews #3 — Alex Coulombe",
    date: "2022",
    dateISO: "2022-06-15T00:00:00Z",
    url: "https://twitter.com/i/spaces/1OdJrBeVkPkJX?s=20",
  },
  {
    slug: "performing-for-motion-capture-book-2022",
    kind: "Press",
    outlet: "Performing for Motion Capture (book)",
    title: "Interviewee — John Dower & Pascal Langdale",
    date: "2022",
    dateISO: "2022-06-15T00:00:00Z",
    url: "https://www.bloomsbury.com/uk/performing-for-motion-capture-9781350211254/",
  },
  {
    slug: "becoming-cg-pro-podcast-2022",
    kind: "Podcast",
    outlet: "Becoming CG Pro",
    title: "Guest",
    date: "2022",
    dateISO: "2022-06-15T00:00:00Z",
  },
  {
    slug: "nyt-stockhausen-gruppen-2012",
    kind: "Work Featured",
    outlet: "The New York Times",
    title: "Stockhausen's Gruppen at Park Avenue Armory — his VR visualization rendering runs at the top of the piece; he isn't named in the text",
    date: "Jun 2012",
    dateISO: "2012-06-24T00:00:00Z",
    url: "https://www.nytimes.com/2012/06/24/arts/music/stockhausens-gruppen-at-park-avenue-armory.html",
  },
  {
    slug: "uploadvr-meta-orion-2024",
    kind: "Press",
    outlet: "UploadVR",
    title: "Meta Orion Glasses Hands-On: Viewing AR's Future As A VR Developer",
    date: "Sep 2024",
    dateISO: "2024-09-15T00:00:00Z",
    url: "https://www.uploadvr.com/alex-coulombe-orion-glasses-hands-on/",
  },
  {
    slug: "ue-podcast-webxr-pixel-streaming-2023",
    kind: "Podcast",
    outlet: "The (Unofficial) Unreal Engine Podcast",
    title: "Is WebXR Pixel Streaming the Future?",
    date: "2023",
    dateISO: "2023-06-15T00:00:00Z",
    url: "https://youtu.be/QS_SsrxdQGM",
  },
  {
    slug: "ue-podcast-vision-pro-support-2024",
    kind: "Podcast",
    outlet: "The (Unofficial) Unreal Engine Podcast",
    title: "Will Unreal Engine Support Apple Vision Pro?",
    date: "2024",
    dateISO: "2024-06-15T00:00:00Z",
    url: "https://youtu.be/Y8HOQPpkRPg",
  },
];
